### PR TITLE
Allow PATCH as a valid initial method for uploads

### PR DESCRIPTION
**Pull request by sqrrrl**

### CODE REVIEW

**Comment by ejona86** [comment]
This LGTM. In a separate thread it sounded like you were running into some issues when trying to use it. Just ping here or on that separate thread once you feel comfortable with the change and I'll merge it.

Thanks for adding the tests.

**Comment by sqrrrl** [comment]
I verified it works with direct/multipart uploads. There is a separate issue with resumable uploads, but that appears to be an issue on the backend and is reproducible with other client libraries too.

**Comment by ihommani** [comment]
Hi, 

@ejona86 , is there any repo with the release candidate containing this fix available ?
Thx

**Comment by ejona86** [comment]
@ihommani, this repo contains the fix. Do you mean Maven repo? No, but I can make a snapshot and I will be doing a new release soon.

**Comment by ihommani** [comment]
@ejona86 , yes a maven repo. But it's ok for now, I used our own nexus server to host the snapshot.  Waiting for the new release though :)

Thx

**Pull request merged**
